#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lisa.Dobble.Droid.Resource", IsApplication=true)]

namespace Lisa.Dobble.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Lisa.Dobble.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Lisa.Dobble.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_active_month_bg = global::Lisa.Dobble.Droid.Resource.Color.calendar_active_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_bg = global::Lisa.Dobble.Droid.Resource.Color.calendar_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_divider = global::Lisa.Dobble.Droid.Resource.Color.calendar_divider;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_highlighted_day_bg = global::Lisa.Dobble.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_inactive_month_bg = global::Lisa.Dobble.Droid.Resource.Color.calendar_inactive_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_day_bg = global::Lisa.Dobble.Droid.Resource.Color.calendar_selected_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_range_bg = global::Lisa.Dobble.Droid.Resource.Color.calendar_selected_range_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_active = global::Lisa.Dobble.Droid.Resource.Color.calendar_text_active;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_inactive = global::Lisa.Dobble.Droid.Resource.Color.calendar_text_inactive;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selected = global::Lisa.Dobble.Droid.Resource.Color.calendar_text_selected;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selector = global::Lisa.Dobble.Droid.Resource.Color.calendar_text_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_unselectable = global::Lisa.Dobble.Droid.Resource.Color.calendar_text_unselectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::Lisa.Dobble.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::Lisa.Dobble.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_topmargin = global::Lisa.Dobble.Droid.Resource.Dimension.calendar_month_topmargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_medium = global::Lisa.Dobble.Droid.Resource.Dimension.calendar_text_medium;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_small = global::Lisa.Dobble.Droid.Resource.Dimension.calendar_text_small;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.ad16 = global::Lisa.Dobble.Droid.Resource.Drawable.ad16;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.calendar_bg_selector = global::Lisa.Dobble.Droid.Resource.Drawable.calendar_bg_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_grid = global::Lisa.Dobble.Droid.Resource.Id.calendar_grid;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_view = global::Lisa.Dobble.Droid.Resource.Id.calendar_view;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.title = global::Lisa.Dobble.Droid.Resource.Id.title;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.calendar_picker = global::Lisa.Dobble.Droid.Resource.Layout.calendar_picker;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.dialog = global::Lisa.Dobble.Droid.Resource.Layout.dialog;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.month = global::Lisa.Dobble.Droid.Resource.Layout.month;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.week = global::Lisa.Dobble.Droid.Resource.Layout.week;
			global::Xamarin.Forms.Labs.Droid.Resource.String.day_name_format = global::Lisa.Dobble.Droid.Resource.String.day_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.full_date_format = global::Lisa.Dobble.Droid.Resource.String.full_date_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.invalid_date = global::Lisa.Dobble.Droid.Resource.String.invalid_date;
			global::Xamarin.Forms.Labs.Droid.Resource.String.library_name = global::Lisa.Dobble.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Labs.Droid.Resource.String.month_name_format = global::Lisa.Dobble.Droid.Resource.String.month_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell = global::Lisa.Dobble.Droid.Resource.Style.CalendarCell;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_CalendarDate = global::Lisa.Dobble.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_DayHeader = global::Lisa.Dobble.Droid.Resource.Style.CalendarCell_DayHeader;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarTitle = global::Lisa.Dobble.Droid.Resource.Style.CalendarTitle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int calendar_text_selector = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int calendar_text_unselectable = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_text_small = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dice11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dice12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dice13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dice14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dice15 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dice16 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int dice21 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dice22 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dice23 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dice24 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dice25 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int dice26 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dice31 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dice32 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int dice33 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dice34 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int dice35 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int dice36 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int dice41 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int dice42 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int dice43 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int dice44 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int dice45 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int dice46 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int dice51 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int dice52 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int dice53 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int dice54 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int dice55 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dice56 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int dobblemask = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int dobblemasksmall = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int edit = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int info = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int lisalogo = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int logo = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int notset = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int play = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int plus = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int record = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int stop = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tick = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int white = 2130837548;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int calendar_grid = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int calendar_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int month = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int week = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int ApplicationName = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int Hello = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
